In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [2]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [3]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [4]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [5]:
df2=df.sample(frac=1)

In [6]:
df2.shape

(569, 31)

In [7]:
hold_on_data=df2.iloc[0:285,:]

In [8]:
hold_on_data.shape

(285, 31)

In [9]:
hold_on_data

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
544,13.87,20.70,89.77,584.8,0.09578,0.10180,0.036880,0.023690,0.1620,0.06688,...,24.75,99.17,688.6,0.1264,0.20370,0.137700,0.06845,0.2249,0.08492,1
85,18.46,18.52,121.10,1075.0,0.09874,0.10530,0.133500,0.087950,0.2132,0.06022,...,27.68,152.20,1603.0,0.1398,0.20890,0.315700,0.16420,0.3695,0.08579,0
306,13.20,15.82,84.07,537.3,0.08511,0.05251,0.001461,0.003261,0.1632,0.05894,...,20.45,92.00,636.9,0.1128,0.13460,0.011200,0.02500,0.2651,0.08385,1
560,14.05,27.15,91.38,600.4,0.09929,0.11260,0.044620,0.043040,0.1537,0.06171,...,33.17,100.20,706.7,0.1241,0.22640,0.132600,0.10480,0.2250,0.08321,1
164,23.27,22.04,152.10,1686.0,0.08439,0.11450,0.132400,0.097020,0.1801,0.05553,...,28.22,184.20,2403.0,0.1228,0.35830,0.394800,0.23460,0.3589,0.09187,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,11.71,15.45,75.03,420.3,0.11500,0.07281,0.040060,0.032500,0.2009,0.06506,...,18.16,84.16,516.4,0.1460,0.11150,0.108700,0.07864,0.2765,0.07806,1
9,12.46,24.04,83.97,475.9,0.11860,0.23960,0.227300,0.085430,0.2030,0.08243,...,40.68,97.65,711.4,0.1853,1.05800,1.105000,0.22100,0.4366,0.20750,0
55,11.52,18.75,73.34,409.0,0.09524,0.05473,0.030360,0.022780,0.1920,0.05907,...,22.47,81.81,506.2,0.1249,0.08720,0.090760,0.06316,0.3306,0.07036,1
48,12.05,14.63,78.04,449.3,0.10310,0.09092,0.065920,0.027490,0.1675,0.06043,...,20.70,89.88,582.6,0.1494,0.21560,0.305000,0.06548,0.2747,0.08301,1
58,13.05,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,0.1819,0.05501,...,22.25,90.24,624.1,0.1021,0.06191,0.001845,0.01111,0.2439,0.06289,1

In [10]:
df1=df2.iloc[286:569,:]

In [11]:
y=df1.iloc[:,-1]

In [12]:
y

441    0
230    0
217    1
112    1
302    0
      ..
77     0
318    1
195    1
172    0
529    1
Name: target, Length: 283, dtype: int64

In [13]:
X=df1.iloc[:,:-1]

In [14]:
X

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
441,17.270,25.42,112.40,928.8,0.08331,0.11090,0.12040,0.05736,0.1467,0.05407,...,20.38,35.46,132.80,1284.0,0.14360,0.4122,0.5036,0.17390,0.2500,0.07944
230,17.050,19.08,113.40,895.0,0.11410,0.15720,0.19100,0.10900,0.2131,0.06325,...,19.59,24.89,133.50,1189.0,0.17030,0.3934,0.5018,0.25430,0.3109,0.09061
217,10.200,17.48,65.05,321.2,0.08054,0.05907,0.05774,0.01071,0.1964,0.06315,...,11.48,24.47,75.40,403.7,0.09527,0.1397,0.1925,0.03571,0.2868,0.07809
112,14.260,19.65,97.83,629.9,0.07837,0.22330,0.30030,0.07798,0.1704,0.07769,...,15.30,23.73,107.00,709.0,0.08949,0.4193,0.6783,0.15050,0.2398,0.10820
302,20.090,23.86,134.70,1247.0,0.10800,0.18380,0.22830,0.12800,0.2249,0.07469,...,23.68,29.43,158.80,1696.0,0.13470,0.3391,0.4932,0.19230,0.3294,0.09469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,18.050,16.15,120.20,1006.0,0.10650,0.21460,0.16840,0.10800,0.2152,0.06673,...,22.39,18.91,150.10,1610.0,0.14780,0.5634,0.3786,0.21020,0.3751,0.11080
318,9.042,18.90,60.07,244.5,0.09968,0.19720,0.19750,0.04908,0.2330,0.08743,...,10.06,23.40,68.62,297.1,0.12210,0.3748,0.4609,0.11450,0.3135,0.10550
195,12.910,16.33,82.53,516.4,0.07941,0.05366,0.03873,0.02377,0.1829,0.05667,...,13.88,22.00,90.81,600.6,0.10970,0.1506,0.1764,0.08235,0.3024,0.06949
172,15.460,11.89,102.50,736.9,0.12570,0.15550,0.20320,0.10970,0.1966,0.07069,...,18.79,17.04,125.00,1102.0,0.15310,0.3583,0.5830,0.18270,0.3216,0.10100
529,12.070,13.44,77.83,445.2,0.11000,0.09009,0.03781,0.02798,0.1657,0.06608,...,13.45,15.77,86.92,549.9,0.15210,0.1632,0.1622,0.07393,0.2781,0.08052

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [16]:
X

array([[ 0.78555496,  1.49824529,  0.73272672, ...,  0.80591481,
        -0.71460999, -0.28079483],
       [ 0.72593019, -0.04852683,  0.77196387, ...,  2.01487087,
         0.21766427,  0.37209503],
       [-1.13056846, -0.43887941, -1.12515229, ..., -1.27201601,
        -0.15126528, -0.35970274],
       ...,
       [-0.39609965, -0.71944533, -0.43928692, ..., -0.5707012 ,
         0.08754389, -0.86237532],
       [ 0.29500568, -1.80267375,  0.34427895, ...,  0.93823836,
         0.38146287,  0.97939365],
       [-0.62375788, -1.42451969, -0.62370152, ..., -0.69731078,
        -0.28444732, -0.21766851]])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [18]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [19]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [20]:
h_X

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
544,13.87,20.70,89.77,584.8,0.09578,0.10180,0.036880,0.023690,0.1620,0.06688,...,15.05,24.75,99.17,688.6,0.1264,0.20370,0.137700,0.06845,0.2249,0.08492
85,18.46,18.52,121.10,1075.0,0.09874,0.10530,0.133500,0.087950,0.2132,0.06022,...,22.93,27.68,152.20,1603.0,0.1398,0.20890,0.315700,0.16420,0.3695,0.08579
306,13.20,15.82,84.07,537.3,0.08511,0.05251,0.001461,0.003261,0.1632,0.05894,...,14.41,20.45,92.00,636.9,0.1128,0.13460,0.011200,0.02500,0.2651,0.08385
560,14.05,27.15,91.38,600.4,0.09929,0.11260,0.044620,0.043040,0.1537,0.06171,...,15.30,33.17,100.20,706.7,0.1241,0.22640,0.132600,0.10480,0.2250,0.08321
164,23.27,22.04,152.10,1686.0,0.08439,0.11450,0.132400,0.097020,0.1801,0.05553,...,28.01,28.22,184.20,2403.0,0.1228,0.35830,0.394800,0.23460,0.3589,0.09187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,11.71,15.45,75.03,420.3,0.11500,0.07281,0.040060,0.032500,0.2009,0.06506,...,13.06,18.16,84.16,516.4,0.1460,0.11150,0.108700,0.07864,0.2765,0.07806
9,12.46,24.04,83.97,475.9,0.11860,0.23960,0.227300,0.085430,0.2030,0.08243,...,15.09,40.68,97.65,711.4,0.1853,1.05800,1.105000,0.22100,0.4366,0.20750
55,11.52,18.75,73.34,409.0,0.09524,0.05473,0.030360,0.022780,0.1920,0.05907,...,12.84,22.47,81.81,506.2,0.1249,0.08720,0.090760,0.06316,0.3306,0.07036
48,12.05,14.63,78.04,449.3,0.10310,0.09092,0.065920,0.027490,0.1675,0.06043,...,13.76,20.70,89.88,582.6,0.1494,0.21560,0.305000,0.06548,0.2747,0.08301
58,13.05,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,0.1819,0.05501,...,14.23,22.25,90.24,624.1,0.1021,0.06191,0.001845,0.01111,0.2439,0.06289

In [21]:
h_X=sc.fit_transform(h_X)

In [22]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [23]:
x1

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

In [24]:
x2

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [25]:
x3

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])

In [26]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [27]:
df4=df3.T

In [28]:
df4

     0  1  2
0    1  1  1
1    0  0  0
2    1  1  1
3    1  1  1
4    0  0  0
..  .. .. ..
280  1  1  1
281  0  0  0
282  1  1  1
283  1  1  1
284  1  1  1

[285 rows x 3 columns]

In [29]:
lr2=LogisticRegression()

In [30]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [31]:
df4_X

     0  1  2
0    1  1  1
1    0  0  0
2    1  1  1
3    1  1  1
4    0  0  0
..  .. .. ..
280  1  1  1
281  0  0  0
282  1  1  1
283  1  1  1
284  1  1  1

[285 rows x 3 columns]

In [32]:
df4_Y

544    1
85     0
306    1
560    1
164    0
      ..
344    1
9      0
55     1
48     1
58     1
Name: target, Length: 285, dtype: int64

In [33]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [34]:
X_test=sc.fit_transform(X_test)

In [35]:
X_test

array([[-0.49007559, -0.30608155, -0.55389539, ..., -1.68566831,
        -0.67248947, -1.02692878],
       [ 2.00778497,  0.74537468,  1.9363381 , ...,  1.31123203,
        -0.09246539, -1.3448799 ],
       [-0.4057728 ,  0.52889839, -0.42681951, ..., -0.91303761,
        -0.69689642, -0.06071693],
       ...,
       [ 0.89311469,  0.21683518,  0.80173199, ..., -0.03651279,
         0.43300196, -1.00558224],
       [ 1.69867472,  1.54942944,  1.61864839, ...,  0.56866389,
        -0.97685854, -1.21792415],
       [ 0.09379931,  0.20558966,  0.11143763, ...,  1.17711179,
         2.55497123,  1.05098846]])

In [36]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [37]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [38]:
df6=df5.T

In [39]:
df6

    0  1  2
0   1  1  1
1   0  0  0
2   1  1  1
3   1  1  1
4   1  1  1
.. .. .. ..
89  1  1  1
90  1  1  1
91  0  0  0
92  0  0  0
93  0  0  0

[94 rows x 3 columns]

In [40]:
df6_X=df6.iloc[:,:]

In [41]:
final=lr2.predict(df6_X)

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, final)
precision = precision_score(y_test, final, average=None)
recall = recall_score(y_test, final, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.94444444 0.98275862]
recall: [0.97142857 0.96610169]

In [43]:
from sklearn.ensemble import StackingClassifier

In [44]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [45]:
df_X=sc.fit_transform(df_X)

In [46]:
df_X.shape

(569, 30)

In [47]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [48]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [49]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [50]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [51]:
final1=clf.predict(df_X_test)

In [52]:
accuracy_score(df_y_test, final1)

0.9627659574468085

In [53]:
precision = precision_score(df_y_test, final1, average=None)
recall = recall_score(df_y_test, final1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.98550725 0.94957983]
recall: [0.91891892 0.99122807]